templates. new reverse proxy handling
NethServer/nethserver-webtop5 pull request #94
Opened 2021-03-23 14:34 UTC by federicoballarini

2021-03-23 16:20 UTC, Amygos requested changes
You have to add the path  `/var/www/html/webtop/.htaccess` into the list of templates to expand on package update, in the `createlinks` file.

2021-03-23 17:06 UTC, federicoballarini commented
> You have to add the path `/var/www/html/webtop/.htaccess` into the list of templates to expand on package update, in the `createlinks` file.

Yes, you are right. My bad. I missed to report it from dev... :/

2021-03-24 09:53 UTC, Amygos commented
The PR seems ok for me, but before the merge, we need to out a better explanation on why we need it.

2021-03-24 11:09 UTC, gsanchietti requested changes

2021-03-24 11:09 UTC, gsanchietti commented on root/etc/e-smith/templates/var/www/html/webtop/.htaccess/10base
> +RewriteRule .* http://127.0.0.1:58080%\{REQUEST_URI\} [P,L]
This fragment doesn't contain any variable, why is it a template?

Please convert it to a simple static file.

2021-03-24 12:20 UTC, federicoballarini commented on root/etc/e-smith/templates/var/www/html/webtop/.htaccess/10base
> +RewriteRule .* http://127.0.0.1:58080%\{REQUEST_URI\} [P,L]
> This fragment doesn't contain any variable, why is it a template?
> 
> Please convert it to a simple static file.

I need to remove also /var/www/html/.htaccess from createlinks, correct? If an user made a change on .htaccess file, the event nethserver-webtop5-update will not restore it to default. Is this the correct behaviour?

2021-03-24 13:39 UTC, gsanchietti commented on root/etc/e-smith/templates/var/www/html/webtop/.htaccess/10base
> +RewriteRule .* http://127.0.0.1:58080%\{REQUEST_URI\} [P,L]
Yes, remove the entry also from createlinks.
This is not a customizable file: if you change it, WebTop will stop working.
The user should not modify it just like any other file belonging to a RPM and not marked as config file.

2021-03-24 16:07 UTC, gsanchietti requested changes

2021-03-24 16:07 UTC, gsanchietti commented on nethserver-webtop5.spec
> +
You do not this anyore
```suggestion
```

2021-03-24 16:15 UTC, federicoballarini commented on createlinks
> +                     '/etc/webtop/webtop.properties',
Ok... :( :D

2021-03-24 16:16 UTC, gsanchietti commented on createlinks
> +                     '/etc/webtop/webtop.properties',
Just open another PR with this ;)

2021-03-24 16:17 UTC, gsanchietti commented on nethserver-webtop5.spec
>  - WebTop 5 - NethServer/dev#5225
```suggestion
- WebTop 5 - NethServer/dev#5225

```

2021-03-24 16:17 UTC, gsanchietti commented on nethserver-webtop5.spec
> -
Please, avoid also this change

2021-03-24 16:19 UTC, Amygos commented
I have updated the PR's description with the full background explanation.

2021-03-24 16:25 UTC, federicoballarini commented on nethserver-webtop5.spec
> -
Ops... this is clearly an error and I can't remember when I changed it...

2021-03-24 16:28 UTC, federicoballarini commented on createlinks
> +                     '/etc/webtop/webtop.properties',
After merging this I will open it :)

2021-03-24 16:30 UTC, gsanchietti approved these changes
:heavy_check_mark: 

@Amygos you can squash&merge whenever you prefer

2021-03-25 10:51 UTC, Amygos approved these changes

2021-03-25 11:02 UTC, merged